sudo: required
language: php
group: edge
php:
  - 5.6
  - 7.0
  - hhvm

services:
  - docker

before_install:
  - docker run -d -p 127.0.0.1:6379:6379 redis:3
  - docker ps -a

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --dev --no-progress --no-interaction

script:
  - ./vendor/bin/phpunit --verbose $PHPUNIT_FLAGS
